version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - bank-network

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://manojsiriparthi:Manoj2627@manoj-bank.n8ql6.mongodb.net/Bank-App?retryWrites=true&w=majority&appName=Manoj-Bank
      - NODE_ENV=production
      - PORT=5000
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

