version: '3'
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./Frontend/src/.env
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    env_file:
      - ./Backend/.env
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

