version: '3.8'

services:
  # Backend service
  backend:
    build: ./Backend
    expose:
      - "5000"  # Expose backend to other services internally (no need to expose to host)
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=manoj
      - MYSQL_PASSWORD=Manoj@2627
      - MYSQL_DB=bank_app_db
    depends_on:
      - mysql
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    environment:
      - NODE_ENV=production  # Ensure that frontend knows it's running in production
    depends_on:
      - backend
    networks:
      - app-network

  # MySQL database service
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"  # MySQL port exposed
    environment:
      MYSQL_ROOT_PASSWORD: Manoj@2627
      MYSQL_DATABASE: bank_app_db
      MYSQL_USER: manoj
      MYSQL_PASSWORD: Manoj@2627
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:

