apiVersion: v1
kind: Service
metadata:
  name: bankapp-backend
  namespace: three-tier
  labels:
    app: bankapp
    role: backend
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is required
  selector:
    app: bankapp
    role: backend
  ports:
    - protocol: TCP
      port: 80         # The port on which the service is exposed within the cluster
      targetPort: 3500 # The port on the container that the service should forward to

