apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: three-tier
  labels:
    app: bankapp
    role: frontend
spec:
  type: LoadBalancer
  selector:
    app: bankapp
    role: frontend
  ports:
    - protocol: TCP
      port: 80            # The port on which the load balancer will listen
      targetPort: 3000    # The port the frontend container is listening on

