apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-frontend
  namespace: three-tier
  labels:
    app: bankapp
    role: frontend
    env: demo
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: bankapp
      role: frontend
  template:
    metadata:
      labels:
        app: bankapp
        role: frontend
    spec: 
      containers:
      - name: bankapp-frontend
        image: manojsiriparthi/bankapp-frontend:latest # Updated with the public Docker image
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://your-backend-url/api/tasks" # Replace with the actual backend URL
        ports:
        - containerPort: 3000

